
<h1>$R$ $language$ $notes$</h1>

<h2>_Basic calculation_<h2/> 
```
1 + 2
```
[1] 3 

```
5 - 3
```
[1] 2

```
6 * 2
```
[1] 12

```
14 / 7
```
[1] 2

```
2 ^ 3
```
[1] 8

```
25 %% 4
```
[1]1

```
25 %/% 4
```
[1] 6

```
3 * 5 + 2
```
[1] 17


<h2>_Numerical Vectors_<h2/>

```
x <- c(1,2,3)
x
```
[1] 1 2 3

```
y <- 0:10
y
```
[1] 0 1 2 3 4 5 6 7 8 9 10


```
c(x,y)
```
[1]  1  2  3  0  1  2  3  4  5  6  7  8  9 10

```
x[3]
```
[1] 3

```
y[2:5]
```
[1] 1 2 3 4

```
x[-2]
```
[1] 1 3

```
y[-(2:5)]
```
[1] 0 5 6 7 8 9 10

```
y[c(1,3:5)]
```
[1] 0 2 3 4

```
x * 4
```
[1] 4 8 12

```
x ^ 4
```
[1] 1 16 81

```
z <- x+8
z
```
[1] 9 10 11

```
rep(2,5)
```
[1] 2 2 2 2 2

```
rep(seq(4,20,by=2),2)
```
 [1]  4  6  8 10 12 14 16 18 20  4  6  8 10 12 14 16 18 20
 
```
rep(c(1,5),each=4)
```
[1] 1 1 1 1 5 5 5 5

```
rep(c(1,5),c(2,3))
```
[1] 1 1 5 5 5


<h2>_Charecter Vectors_<h2/>

```
colors <- c("green","red")
More <- c("Blue",colors)
More
```
[1] "Blue"  "green" "red" 

```
substr(More,1,3)
```
[1] "Blu" "gre" "red"

```
paste(More,"ball")
```
[1] "Blue ball"  "green ball" "red ball" 

```
paste(More,"ball",collapse=",")
```
[1] "Blue ball,green ball,red ball"

<h2>_Matrix_<h2/>

```
A=matrix(3:8,nrow=3,ncol=2)
A
```
$$\begin{bmatrix}3 & 6\\
4 & 7\\
5 & 8
\end{bmatrix}$$   

```
A[1,]
```
[1] 3 6

```
A[,2]
```
[1] 6 7 8

```
dim(A)            # m x n matrix
```
[1] 3 2  

```
B=cbind(c(1,1,1),c(2,2,2),c(3,3,3))     # Use C/Rbind to construct matrix
B
```
$$\begin{bmatrix}1 & 2 & 3\\
1 & 2 & 3\\
1 & 2 & 3
\end{bmatrix}$$    
    
```
det(B)   # Matrix must be square  
```
[1]0 

>~~det(A)~~

```
diag(B)
```
[1] 1 2 3

```
diag(diag(B))
```
$$\begin{bmatrix}1 & 0 & 0\\
0 & 2 & 0\\
0 & 0 & 3
\end{bmatrix}$$ 

```
t(A)
```
   $$A^{T}=\begin{bmatrix}3 & 4 & 5\\
   6 & 7 & 8\\
   \end{bmatrix}$$ 

```
Low<-B
Low[lower.tri(B,diag=TRUE)] <- 0
Low
```
$$\begin{bmatrix}0 & 2 & 3\\
0 & 0 & 3\\
0 & 0 & 0
\end{bmatrix}$$ 

```
t(A) %*% A
```
   $$A^{T}A=\begin{bmatrix}50 & 86\\
   86 & 149\\
   \end{bmatrix}$$
   
```
C=cbind(c(1,2,6),c(2,8,4),c(3,6,9))     
C
solve(C)
```
$$C=\begin{bmatrix}1 & 2 & 6\\          
2 & 8 & 4\\
3 & 6 & 9
\end{bmatrix}$$ 
$$C^{-1}=\begin{bmatrix}-1.333333 & 0.166667 &  3.333333e-01\\
-0.500000 & 0.2500000 & 8.326673e-18\\
1.111111 & -0.2222222 & -1.111111e-01
\end{bmatrix}$$ 

<h2>_Basic statistical Graphic_<h2/>
   
```
VADeaths
barplot(VADeaths,beside=TRUE,legend=TRUE,ylab="Deaths per 1000",main="Deaths rates in virginia")
```
<h3>_Bar Plot_<h3/> 
```{r,echo=FALSE}
VADeaths
barplot(VADeaths,beside=TRUE,legend=TRUE,ylab="Deaths per 1000",main="Deaths rates in virginia")
```

<h3>_Dot Chart_<h3/> 
```
dotchart(VADeaths,main="Deaths rates in virginia")
```
```{r,echo=FALSE}
dotchart(VADeaths,main="Deaths rates in virginia")
```


<h3>_Pie Chart_<h3/> 
```
sizes <- c(37,63)
Labels <- c("Male","Female")
pie(sizes,Labels,col=c("AntiqueWhite","Beige"))
```
```{r,echo=FALSE}
sizes <- c(37,63)
Labels <- c("Male","Female")
pie(sizes,Labels,col=c("AntiqueWhite","Beige"))
```

<h3>_Histogram_<h3/> 
```
x=rpois(1000,5)
hist(x)
```
```{r,echo=FALSE}
x=rpois(1000,5)
hist(x)
```

<h3>_Box Plot_<h3/>

```
boxplot(Sepal.Length~Species,data = iris,ylab="Sepal length(cm)",main="Iris Measurements")
```
```{r,echo=FALSE}
boxplot(Sepal.Length~Species,data = iris,ylab="Sepal length(cm)",main="Iris Measurements")
```

<h3>_Scatter Plot_<h3/>


```
plot(cars,axes=F)
box(lty=1)
axis(side=1,at=seq(4:28),cex.axis=0.5)
axis(side=2,at=seq(0,120,10),cex.axis=0.5,las=1)
points(23,60,col="blue")
points(26,61,col="blue")
```
```{r,echo=FALSE}
plot(cars,axes=F)
box(lty=1)
axis(side=1,at=seq(4:28),cex.axis=0.5)
axis(side=2,at=seq(0,120,10),cex.axis=0.5,las=1)
points(23,60,col="blue")
points(26,61,col="blue")
```

<h4>_Adding Regression line_<h4/>

```
plot(cars,axes=F)
box(lty=1)
axis(side=1,at=seq(4:28),cex.axis=0.5)
axis(side=2,at=seq(0,120,10),cex.axis=0.5,las=1)
points(23,60,col="blue")
abline(a = 1,b = 2.5,col="blue",lty=6)
```
```{r,echo=FALSE}
plot(cars,axes=F)
box(lty=1)
axis(side=1,at=seq(4:28),cex.axis=0.5)
axis(side=2,at=seq(0,120,10),cex.axis=0.5,las=1)
points(23,60,col="blue")
abline(a = 1,b = 2.5,col="blue",lty=6)
```


<h3>_Stem and leaves_<h3/>

```
stem(VADeaths)
```
* 0 | 89224589
* 2 | 047157 
* 4 | 1045 
* 6 | 61 


<h3>_QQ Plot_<h3/>

```
X <- rnorm(10000)
A <- rnorm(10000)
B <- rnorm(10000,mean=50,sd=20)
C <- rt(10000,df=3)
D <- exp(rnorm(10000))
qqplot(X,A,main="A and X are same")
qqplot(X,B,main="B is rescaled X")
qqplot(X,C,main="C has heavier tails")
qqplot(X,D,main="D is skewed right")
```

```{r,fig.width=4,echo=FALSE}
X <- rnorm(10000)
A <- rnorm(10000)
B <- rnorm(10000,mean=50,sd=20)
C <- rt(10000,df=3)
D <- exp(rnorm(10000))
qqplot(X,A,main="A and X are same")
qqplot(X,B,main="B is rescaled X")
qqplot(X,C,main="C has heavier tails")
qqplot(X,D,main="D is skewed right")
```

